src/blog/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from blog.sitemaps import PostSitemap

from . import views

app_name = "blog"
sitemaps = {"posts": PostSitemap}

urlpatterns = [
    path("", views.PostListView.as_view(), name="posts"),
    path("<slug:slug>/", views.PostDetailView.as_view(), name="blog-detail"),
    path("tutorials/tags/<str:tag_name>/", views.blog_tag, name="blog_tag"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

src/course/urls.py
from django.urls import path
from . import views

app_name = "course"


urlpatterns = [
    path("", views.CourseListView.as_view(), name="courses"),
    path(
        "<slug:slug>/overview",
        views.CourseOverviewView.as_view(),
        name="course-overview",
    ),
    path("<slug:slug>/", views.CourseDetailView.as_view(), name="course-detail"),
    path(
        "subscribe-user-to-course/<slug:course_slug>/",
        views.subscribe_user_to_course,
        name="subscribe_user_to_course",
    ),
    path(
        "category/<str:category>/",
        views.CategoryCourseList.as_view(),
        name="course-by-category",
    ),
]

src/dashboard/urls.py
from django.urls import path
from course import views as course_views
from blog import views as blog_views
from dashboard.views import staff as staff_views
from dashboard.views import student as student_views
from dashboard.views import teacher as teacher_views
from dashboard.views import shared as shared_views

app_name = "dashboard"

urlpatterns = [
    path("", shared_views.dashboard_view, name="dashboard"),
    # staff
    path("staff/", staff_views.StaffView.as_view(), name="staff"),
    path("staff/logs/", staff_views.UserLogList.as_view(), name="logs"),
    path(
        "staff/all-courses/", staff_views.AllCoursesView.as_view(), name="all_courses"
    ),
    path(
        "staff/published-courses/",
        staff_views.PublishedCoursesView.as_view(),
        name="published_courses",
    ),
    path(
        "staff/unpublished-courses/",
        staff_views.UnPublishedCoursesView.as_view(),
        name="unpublished_courses",
    ),
    path(
        "staff/all-tutorials/",
        staff_views.AllTutorialsView.as_view(),
        name="all_tutorials",
    ),
    path(
        "staff/published-tutorials/",
        staff_views.PublishedTutorialsView.as_view(),
        name="published_tutorials",
    ),
    path(
        "staff/unpublished-tutorials/",
        staff_views.UnPublishedTutorialsView.as_view(),
        name="unpublished_tutorials",
    ),
    path(
        "staff/all-teachers/",
        staff_views.AllTeachersView.as_view(),
        name="all_teachers",
    ),
    path(
        "staff/invalid-teachers/",
        staff_views.InvalidTeachersView.as_view(),
        name="invalid_teachers",
    ),
    path(
        "staff/valid-teachers/",
        staff_views.ValidTeachersView.as_view(),
        name="valid_teachers",
    ),
    path(
        "staff/all-students/",
        staff_views.AllStudentsView.as_view(),
        name="all_students",
    ),
    path(
        "staff/enrolled-students/",
        staff_views.EnrolledStudentsView.as_view(),
        name="enrolled_students",
    ),
    path(
        "staff/no-enrolled-students/",
        staff_views.NoEnrolledStudentsView.as_view(),
        name="no_enrolled_students",
    ),
    path("publish-tutorial/", staff_views.publish_tutorial, name="publish-tutorial"),
    path("publish-course/", staff_views.publish_course, name="publish-course"),
    # student
    path(
        "student/courses/",
        course_views.StudentCourseListView.as_view(),
        name="enrolled-courses",
    ),
    path("student/", student_views.StudentView.as_view(), name="student"),
    # teacher
    path("instructor/", teacher_views.InstructorView.as_view(), name="instructor"),
    path("courses/", teacher_views.CourseListView.as_view(), name="courses"),
    path(
        "course/create/", teacher_views.CourseCreateView.as_view(), name="create-course"
    ),
    path(
        "course/edit/<slug:slug>",
        teacher_views.CourseUpdateView.as_view(),
        name="update-course",
    ),
    path(
        "manage-course/<slug:slug>",
        teacher_views.CourseManagementView.as_view(),
        name="manage-course",
    ),
    path(
        "delete-chapter/<slug:slug>/",
        teacher_views.delete_chapter,
        name="delete-chapter",
    ),
    path(
        "draft-chapter/<int:id>/",
        teacher_views.draft_chapter,
        name="draft-chapter",
    ),
    path(
        "manage-chapter/<slug:slug>",
        teacher_views.ChapterManagementView.as_view(),
        name="manage-chapter",
    ),
    path(
        "add-lesson/<slug:slug>/",
        teacher_views.LessonCreateView.as_view(),
        name="create-lesson",
    ),
    path(
        "update-lesson/<int:id>/",
        teacher_views.update_lesson,
        name="update-lesson",
    ),
    path(
        "delete-lesson/<slug:slug>/",
        teacher_views.delete_lesson,
        name="delete-lesson",
    ),
    path("add-quiz/<slug:slug>/", teacher_views.create_quiz, name="create-quiz"),
    path(
        "update-quiz/<slug:slug>/",
        teacher_views.update_quiz,
        name="update-quiz",
    ),
    path(
        "delete-quiz/<slug:slug>/",
        teacher_views.delete_quiz,
        name="delete-quiz",
    ),
    path(
        "delete-question/<int:id>/",
        teacher_views.delete_question,
        name="delete-question",
    ),
    path(
        "delete-answer/<int:id>/",
        teacher_views.delete_answer,
        name="delete-answer",
    ),
    path(
        "manage-quiz/<slug:slug>",
        teacher_views.ChapterManagementView.as_view(),
        name="manage-quiz",
    ),
    path(
        "submit-course/<slug:slug>", teacher_views.submit_course, name="submit-course"
    ),
    path("draft-course/", teacher_views.draft_course, name="draft-course"),
    # shared
    path("tutorials/", shared_views.TutorialListView.as_view(), name="tutorials"),
    path(
        "tutorial/create/",
        shared_views.TutorialCreateView.as_view(),
        name="create-tutorial",
    ),
    path(
        "tutorial/edit/<int:pk>",
        shared_views.TutorialUpdateView.as_view(),
        name="update-tutorial",
    ),
    path("submit-tutorial/", shared_views.submit_tutorial, name="submit-tutorial"),
    path("draft-tutorial/", shared_views.draft_tutorial, name="draft-tutorial"),
    path(
        "tutorials/<str:slug>/overview/",
        shared_views.tutorial_overview,
        name="tutorial_overview",
    ),
    path(
        "teacher/courses/",
        course_views.TeacherCourseListView.as_view(),
        name="created-courses",
    ),
    path(
        "teacher/<slug:slug>/",
        course_views.TeacherChapterListCreateView.as_view(),
        name="add-chapter",
    ),
    path(
        "teacher/<slug:slug>/lesson/",
        course_views.TeacherLessonListCreateView.as_view(),
        name="add-lesson",
    ),
    path(
        "author/posts/",
        blog_views.PostListCreateView.as_view(),
        name="posts-management",
    ),
]

src/xarala/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    path("x-yarou/", admin.site.urls),
    path("graphql/", csrf_exempt(GraphQLView.as_view(graphiql=settings.DEBUG))),
    path("", include("pages.urls", namespace="pages")),
    path("courses/", include("course.urls", namespace="course")),
    path("podcasts/", include("podcast.urls", namespace="podcast")),
    path("users/", include("users.urls")),
    path("tutorials/", include("blog.urls", namespace="blog")),
    path("paths/", include("learning_path.urls", namespace="learning_path")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("news/", include("events.urls", namespace="events")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("order.urls", namespace="orders")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("search/", include("search.urls", namespace="search")),
    path("summernote/", include("django_summernote.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/course/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from users.decorators import teacher_required, student_required
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from .models import Course, Chapter, Lesson, Category
from .forms import CreateCourse, CreateChapter, CreateLesson
from userlogs.models import UserLog

# from .tasks import enroll_course


class CourseListView(ListView):
    queryset = Course.objects.published()
    paginate_by = 6
    context_object_name = "courses"
    template_name = "course_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context


class CourseOverviewView(DetailView):
    model = Course
    template_name = "course_overview.html"

    def get_context_data(self, **kwargs):
        student = self.request.user
        context = super().get_context_data(**kwargs)
        button_text = "Poursuivre"
        if (
            student.is_authenticated
            and context.get("course") in student.courses_enrolled.all()
        ):
            pass
        else:
            button_text = "S'inscrire"
        context["button_text"] = button_text
        return context


@method_decorator([login_required], name="dispatch")
class CourseDetailView(DetailView):
    model = Course
    template_name = "course_detail.html"

    def get_context_data(self, **kwargs):
        slug = self.request.GET.get("lecture")
        lesson = Lesson.objects.get(slug=slug)
        context = super().get_context_data(**kwargs)
        context["lesson"] = lesson
        return context


@login_required(login_url="login")
def subscribe_user_to_course(request, course_slug):
    values = {"error": "", "has_error": 0}
    course = get_object_or_404(Course, slug=course_slug)
    student = request.user
    try:
        if student.is_authenticated:
            if course not in student.courses_enrolled.all():
                student.courses_enrolled.add(course)
                # enroll_course.delay(student.email, course.title)
                UserLog.objects.create(
                    action=f"Enrolled {course} course",
                    user_type="Student",
                    user=student,
                )
                messages.success(request, "Formation enrollée...")
                return redirect(f"/courses/{course.slug}/overview")
            else:
                return redirect(f"/courses/{course.slug}/overview")
    except Exception:
        return JsonResponse(values)


@method_decorator([student_required], name="dispatch")
class StudentCourseListView(ListView):
    def get_queryset(self):
        student = self.request.user
        return student.courses_enrolled.all()

    context_object_name = "courses"


@method_decorator([teacher_required], name="dispatch")
class TeacherCourseListView(ListView, CreateView):
    form_class = CreateCourse
    template_name = "teacher/manage-course.html"

    def get(self, request, *args, **kwargs):
        teacher = self.request.user
        courses = teacher.courses_created.all()
        form = self.form_class()
        title = "Vos Formations"
        return render(
            request,
            self.template_name,
            {"form": form, "courses": courses, "title": title},
        )

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        teacher = self.request.user
        if form.is_valid():
            title = form.cleaned_data.get("title")
            level = form.cleaned_data.get("level")
            language = form.cleaned_data.get("language")
            published = form.cleaned_data.get("published")
            description = form.cleaned_data.get("description")
            thumbnail = form.cleaned_data.get("thumbnail")
            course = Course(
                title=title,
                level=level,
                language=language,
                description=description,
                published=published,
                thumbnail=thumbnail,
                teacher=teacher,
            )
            course.save()
            UserLog.objects.create(
                action=f"Created {title} course", user_type="Instructeur", user=teacher
            )
            return redirect("course:created-courses")

        return render(request, self.template_name, {"form": form})


class TeacherChapterListCreateView(DetailView, CreateView):
    form_class = CreateChapter
    template_name = "teacher/add-chapter.html"

    def get(self, request, *args, **kwargs):
        course_id = request.GET.get("course_id")
        course = Course.objects.get(pk=int(course_id))
        chapters = course.course_chapters.all()
        form = self.form_class()
        return render(request, self.template_name, {"form": form, "chapters": chapters})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            course_id = request.GET.get("course_id")
            chapter = Chapter(name=name)
            chapter.save()
            course = Course.objects.get(pk=int(course_id))
            course.course_chapters.add(chapter)
            return redirect(f"/dashboard/teacher/{course.slug}/?course_id={course_id}")

        return render(request, self.template_name, {"form": form})


@method_decorator([teacher_required], name="dispatch")
class TeacherLessonListCreateView(DetailView, CreateView):
    form_class = CreateLesson
    template_name = "teacher/add-lesson.html"

    def get(self, request, *args, **kwargs):
        chapter_id = request.GET.get("chapter_id")
        chapter = Chapter.objects.get(pk=int(chapter_id))
        lessons = chapter.course_lessons.all()
        form = self.form_class()
        return render(request, self.template_name, {"form": form, "lessons": lessons})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get("title")
            video_link = form.cleaned_data.get("video_id")
            if "www.youtube.com/" or "https://youtu.be/" in video_link:
                video_id = video_link[-11:]
            else:
                video_id = form.cleaned_data.get("video_id")
            text = form.cleaned_data.get("text")
            platform = form.cleaned_data.get("platform")
            chapter_id = request.GET.get("chapter_id")
            lesson = Lesson(
                title=title,
                video_id=video_id,
                text=text,
                platform=platform,
                video_url=video_link,
            )
            lesson.save()
            chapter = Chapter.objects.get(pk=int(chapter_id))
            chapter.course_lessons.add(lesson)
            return redirect(
                f"/dashboard/teacher/{chapter.slug}/lesson/?chapter_id={chapter_id}"
            )

        return render(request, self.template_name, {"form": form})


# categories


class CategoryCourseList(ListView):
    template_name = "courses_by_category.html"
    paginate_by = 2

    def get_queryset(self):
        self.category = get_object_or_404(Category, name=self.kwargs["category"])
        return Course.objects.filter(categories__name=self.category)

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in the publisher
        context["category"] = self.category
        return context


class ProfessionalTrainingView(TemplateView):
    template_name = "professional_training.html"


def generate_course_invoice(request, id):
    pass
    # folder = get_object_or_404(Folder, pk=id)
    # try:
    #     invoice_date = datetime.now()
    #     context = {"folder": folder, "invoice_date": invoice_date}
    #     html_string = render_to_string("finance/generate_invoice.html", context)
    #     response = HttpResponse(content_type="application/pdf")
    #     response["Content-Disposition"] = f"inline; filename=invoice{folder.id}.pdf"
    #     html = HTML(string=html_string, base_url=request.build_absolute_uri())
    #     html.write_pdf(
    #         response, presentational_hints=True,
    #     )
    #     return response
    # except Exception as e:
    #     return HttpResponse(f"<h2>{e}</h2> <a href='/'>Accueil</a>")

src/dashboard/templates/instructor/courses.html
{% extends "_dashboard_base.html" %} {% load static %} {% load crispy_forms_tags %} {% block title %} {{ title }} {% endblock title %} {% block sidebar %} {% include "partials/_sidebar_instructor.html" %} {% endblock sidebar %} {% block content %}

<div class="row">
    <div class="col-lg-12">
        <h2 class="st_title"><i class="uil uil-book-alt"></i>Cours</h2>
    </div>
    <div class="col-md-12">
        <div class="card_dash1">
            <div class="card_dash_left1">
                <i class="uil uil-video"></i>
                <h1>Passez à la création de vos cours</h1>
            </div>
            <div class="card_dash_right1">
                <button class="create_btn_dash" onclick="window.location.href = 'create_new_course.html';">Créer votre cours</button>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="my_courses_tabs">
            <div class="table-responsive mt-30">
                <table class="table ucp-table">
                    <thead class="thead-s">
                        <tr>
                            <th class="text-center" scope="col">#</th>
                            <th>Titre</th>
                            <th class="text-center" scope="col">Date de création</th>
                            <th class="text-center" scope="col">Prix (F CFA)</th>
                            <th class="text-center" scope="col">Etudiants</th>
                            <th class="text-center" scope="col">Statut</th>
                            <th class="text-center" scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for course in courses %}
                        <tr>
                            <td class="text-center">{{ forloop.counter }}</td>
                            <td>{{ course.title }}</td>
                            <td class="text-center">{{ course.date_created|date:"D d M Y" }}</td>
                            <td class="text-center">{{ course.price|floatformat|default_if_none:"0" }}</td>
                            <td class="text-center">{{ course.students.count|default_if_none:"0" }}</td>
                            <td class="text-center"><b class="course_active">
                                    {% if course.published %}
                                        Publié
                                    {% else %}
                                        En attente
                                    {% endif %}
                                        </b></td>
                            <td class="text-center">
                                <div class="dropdown">
                                    <a class="btn" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-ellipsis-v"></i>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <button class="btn btn-sm">
                                            <a href="{% url 'dashboard:update-course' course.id %}" title="Edit" class="dropdown-item">Modifier</a>
                                        </button>
                                        <button class="btn btn-sm">
                                            <a href="{% url 'course:course-overview' course.slug %}" title="View" class="dropdown-item">Détails</a>
                                        </button>
                                        <form id="delete-form" action="{% url 'dashboard:delete-course' course.id %}" method="post">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-sm">
                                                <a  onclick="return confirm('Are you sure you want to delete this item?');" title="Delete" class="dropdown-item">Supprimer</i></a>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>

                {% if courses.has_other_pages %}
                <div class="main-p-pagination text-center">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">

                            {% if courses.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ courses.previous_page_number }}" aria-label="Previous">
									 &laquo;
								</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" aria-label="Previous">
									 &laquo;
								</a>
                            </li>
                            {% endif %} {% for i in courses.paginator.page_range %} {% if courses.number == i %}
                            <li class="page-item"><a class="page-link active" href="#">{{ i }}</a></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %} {% endfor %} {% if courses.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ courses.next_page_number }}" aria-label="Next">
									&raquo; 
								</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" aria-label="Next">
									&raquo; 
								</a>
                            </li>
                            {% endif %}

                        </ul>
                    </nav>
                </div>
                {% endif %}

            </div>

        </div>
    </div>
</div>

{% endblock %}

src/dashboard/templates/instructor/dashboard.html
{% extends "_dashboard_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} {% endblock title %}
{% block sidebar %} {% include "partials/_teacher_sidebar.html" %}
{% endblock sidebar %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h2 class="st_title">
            <i class="uil uil-apps"></i>Tableau de bord Instructeur
        </h2>
    </div>
    <div class="col-xl-4 col-lg-6 col-md-6">
        <div class="card_dash">
            <div class="card_dash_left">
                <h5>Total des ventes (F CFA)</h5>
                <h2>{{ total_sales|floatformat|default_if_none:"0" }}</h2>
                <span class="crdbg_1">New $50</span>
            </div>
            <div class="card_dash_right">
                <img src="{% static 'images/dashboard/achievement.svg'%}" alt="" />
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-6 col-md-6">
        <div class="card_dash">
            <div class="card_dash_left">
                <h5>Nombre total d'inscrits</h5>
                <h2>{{ total_enroll|default_if_none:"0" }}</h2>
                <span class="crdbg_2">New 125</span>
            </div>
            <div class="card_dash_right">
                <img src="{% static 'images/dashboard/graduation-cap.svg' %}" alt="" />
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-6 col-md-6">
        <div class="card_dash">
            <div class="card_dash_left">
                <h5>Nombre de cours total</h5>
                <h2>{{ courses_published.count|default_if_none:"0" }}</h2>
                <span class="crdbg_3">New 5</span>
            </div>
            <div class="card_dash_right">
                <img src="{% static 'images/dashboard/online-course.svg' %}" alt="" />
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card_dash1">
            <div class="card_dash_left1">
                <i class="uil uil-video"></i>
                <h1>Passez à la création de vos propres cours</h1>
            </div>
            <div class="card_dash_right1">
                <button class="create_btn_dash" onclick=window.location.href='{% url "dashboard:create-course" %}'>
                    Créer votre cours
                </button>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-6 col-lg-6 col-md-6">
        <div class="section3125 mt-50">
            <h4 class="item_title">Performance des derniers cours</h4>
            <div class="la5lo1">
                <div class="owl-carousel courses_performance owl-theme">
                    {% for course in courses_published %}
                    <div class="item">
                        <div class="fcrse_1">
                            <a href="{% url 'course:course-overview' course.slug %}" class="fcrse_img">
                                <img src="
                    {% if course.thumbnail %} {{ course.thumbnail.url }}
                    {% else %} {% static 'images/courses/img-1.jpg' %}
                    {% endif %}
                    " alt="" />
                                <div class="course-overlay"></div>
                            </a>
                            <div class="fcrse_content">
                                <div class="vdtodt">
                                    <span class="vdt14">{{ course.date_created|date:"d-m-Y" }}</span>
                                </div>
                                <a href="#" class="crsedt145">{{ course.title }}</a>
                                <div class="allvperf">
                                    <div class="crse-perf-left">Prix</div>
                                    <div class="crse-perf-right">
                                        {{ course.price|floatformat|default_if_none:"0" }} F CFA
                                    </div>
                                </div>
                                <div class="allvperf">
                                    <div class="crse-perf-left">Nombre d'inscrits</div>
                                    <div class="crse-perf-right">
                                        {{ course.students.count|default_if_none:"0" }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-lg-6 col-md-6">
        <div class="section3125 mt-50">
            <h4 class="item_title">Cours en attente</h4>
            <div class="la5lo1">
                <div class="fcrse_1">
                    <div class="fcrse_content">
                        {% for course in courses_unpublished %}
                        <div class="upcming_card">
                            <a href="#" class="crsedt145">{{ course.title }}<span class="pndng_145">Pending</span></a>
                            <p class="submit-course">
                                Submitted<span>{{ course.date_created|date:"d-m-Y" }}</span>
                            </p>
                            <a href="#" class="delete_link10">Delete</a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

src/dashboard/templates/instructor/edit-quiz.html
{% extends "_dashboard_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} {% endblock title %}
{% block sidebar %}
{% include "partials/_sidebar_dashboard.html" %}
{% endblock sidebar %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h2 class="st_title">
            <i class="uil uil-analysis"></i>Modifier le quiz :
            <span class="text-primary">{{ quiz.title }}</span>
        </h2>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="course__form mb-4">
            <form method="POST" action="{% url 'dashboard:update-quiz' quiz.chapter.slug %}">
                {% csrf_token %}
                <div class="general_info10">
                    <div class="row">
                        {{ form.non_field_errors }}
                        <div class="col-12">
                            <small id="titleHelp" class="text-danger">
                                {{ form.title.errors }}
                            </small>
                            <div class="ui search focus mt-10 lbel25">
                                <label for="{{ form.title.id_for_label }}">Titre*</label>
                                <div class="ui left icon input swdh19">
                                    {{ form.title }}
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <small id="descriptionHelp" class="text-danger">
                                {{ form.description.errors }}
                            </small>
                            <div class="ui search focus mt-10 lbel25">
                                <label for="{{ form.description.id_for_label }}">Description*</label>
                                <div class="ui left icon input swdh19">
                                    {{ form.description }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 mt-30">
                            <button type="submit" class="create_btn_dash submit-editted-lesson-data">
                                Enregistrer
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}