src/blog/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from blog.sitemaps import PostSitemap

from . import views

app_name = "blog"
sitemaps = {"posts": PostSitemap}

urlpatterns = [
    path("", views.PostListView.as_view(), name="posts"),
    path("<slug:slug>/", views.PostDetailView.as_view(), name="blog-detail"),
    path("tutorials/tags/<str:tag_name>/", views.blog_tag, name="blog_tag"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

src/course/urls.py
from django.urls import path
from . import views

app_name = "course"


urlpatterns = [
    path("", views.CourseListView.as_view(), name="courses"),
    path(
        "<slug:slug>/overview",
        views.CourseOverviewView.as_view(),
        name="course-overview",
    ),
    path("<slug:slug>/", views.CourseDetailView.as_view(), name="course-detail"),
    path(
        "subscribe-user-to-course/<slug:course_slug>/",
        views.subscribe_user_to_course,
        name="subscribe_user_to_course",
    ),
    path(
        "category/<str:category>/",
        views.CategoryCourseList.as_view(),
        name="course-by-category",
    ),
]

src/dashboard/urls.py
from django.urls import path
from course import views as course_views
from blog import views as blog_views
from dashboard.views import staff as staff_views
from dashboard.views import student as student_views
from dashboard.views import teacher as teacher_views
from dashboard.views import shared as shared_views

app_name = "dashboard"

urlpatterns = [
    path("", shared_views.dashboard_view, name="dashboard"),
    # staff
    path("staff/", staff_views.StaffView.as_view(), name="staff"),
    path("staff/logs/", staff_views.UserLogList.as_view(), name="logs"),
    path(
        "staff/all-courses/", staff_views.AllCoursesView.as_view(), name="all_courses"
    ),
    path(
        "staff/published-courses/",
        staff_views.PublishedCoursesView.as_view(),
        name="published_courses",
    ),
    path(
        "staff/unpublished-courses/",
        staff_views.UnPublishedCoursesView.as_view(),
        name="unpublished_courses",
    ),
    path(
        "staff/all-tutorials/",
        staff_views.AllTutorialsView.as_view(),
        name="all_tutorials",
    ),
    path(
        "staff/published-tutorials/",
        staff_views.PublishedTutorialsView.as_view(),
        name="published_tutorials",
    ),
    path(
        "staff/unpublished-tutorials/",
        staff_views.UnPublishedTutorialsView.as_view(),
        name="unpublished_tutorials",
    ),
    path(
        "staff/all-teachers/",
        staff_views.AllTeachersView.as_view(),
        name="all_teachers",
    ),
    path(
        "staff/invalid-teachers/",
        staff_views.InvalidTeachersView.as_view(),
        name="invalid_teachers",
    ),
    path(
        "staff/valid-teachers/",
        staff_views.ValidTeachersView.as_view(),
        name="valid_teachers",
    ),
    path(
        "staff/all-students/",
        staff_views.AllStudentsView.as_view(),
        name="all_students",
    ),
    path(
        "staff/enrolled-students/",
        staff_views.EnrolledStudentsView.as_view(),
        name="enrolled_students",
    ),
    path(
        "staff/no-enrolled-students/",
        staff_views.NoEnrolledStudentsView.as_view(),
        name="no_enrolled_students",
    ),
    path("publish-tutorial/", staff_views.publish_tutorial, name="publish-tutorial"),
    path("publish-course/", staff_views.publish_course, name="publish-course"),
    # student
    path(
        "student/courses/",
        course_views.StudentCourseListView.as_view(),
        name="enrolled-courses",
    ),
    path("student/", student_views.StudentView.as_view(), name="student"),
    # teacher
    path("instructor/", teacher_views.InstructorView.as_view(), name="instructor"),
    path("courses/", teacher_views.CourseListView.as_view(), name="courses"),
    path(
        "course/create/", teacher_views.CourseCreateView.as_view(), name="create-course"
    ),
    path(
        "course/edit/<slug:slug>",
        teacher_views.CourseUpdateView.as_view(),
        name="update-course",
    ),
    path(
        "manage-course/<slug:slug>",
        teacher_views.CourseManagementView.as_view(),
        name="manage-course",
    ),
    path(
        "delete-chapter/<slug:slug>/",
        teacher_views.delete_chapter,
        name="delete-chapter",
    ),
    path(
        "draft-chapter/<int:id>/",
        teacher_views.draft_chapter,
        name="draft-chapter",
    ),
    path(
        "manage-chapter/<slug:slug>",
        teacher_views.ChapterManagementView.as_view(),
        name="manage-chapter",
    ),
    path(
        "add-lesson/<slug:slug>/",
        teacher_views.LessonCreateView.as_view(),
        name="create-lesson",
    ),
    path(
        "update-lesson/<int:id>/",
        teacher_views.update_lesson,
        name="update-lesson",
    ),
    path(
        "delete-lesson/<slug:slug>/",
        teacher_views.delete_lesson,
        name="delete-lesson",
    ),
    path("add-quiz/<slug:slug>/", teacher_views.create_quiz, name="create-quiz"),
    path(
        "update-quiz/<slug:slug>/",
        teacher_views.update_quiz,
        name="update-quiz",
    ),
    path(
        "delete-quiz/<slug:slug>/",
        teacher_views.delete_quiz,
        name="delete-quiz",
    ),
    path(
        "delete-question/<int:id>/",
        teacher_views.delete_question,
        name="delete-question",
    ),
    path(
        "delete-answer/<int:id>/",
        teacher_views.delete_answer,
        name="delete-answer",
    ),
    path(
        "manage-quiz/<slug:slug>",
        teacher_views.ChapterManagementView.as_view(),
        name="manage-quiz",
    ),
    path(
        "submit-course/<slug:slug>", teacher_views.submit_course, name="submit-course"
    ),
    path("draft-course/", teacher_views.draft_course, name="draft-course"),
    # shared
    path("tutorials/", shared_views.TutorialListView.as_view(), name="tutorials"),
    path(
        "tutorial/create/",
        shared_views.TutorialCreateView.as_view(),
        name="create-tutorial",
    ),
    path(
        "tutorial/edit/<int:pk>",
        shared_views.TutorialUpdateView.as_view(),
        name="update-tutorial",
    ),
    path("submit-tutorial/", shared_views.submit_tutorial, name="submit-tutorial"),
    path("draft-tutorial/", shared_views.draft_tutorial, name="draft-tutorial"),
    path(
        "tutorials/<str:slug>/overview/",
        shared_views.tutorial_overview,
        name="tutorial_overview",
    ),
    path(
        "teacher/courses/",
        course_views.TeacherCourseListView.as_view(),
        name="created-courses",
    ),
    path(
        "teacher/<slug:slug>/",
        course_views.TeacherChapterListCreateView.as_view(),
        name="add-chapter",
    ),
    path(
        "teacher/<slug:slug>/lesson/",
        course_views.TeacherLessonListCreateView.as_view(),
        name="add-lesson",
    ),
    path(
        "author/posts/",
        blog_views.PostListCreateView.as_view(),
        name="posts-management",
    ),
]

src/learning_path/urls.py
from django.urls import path
from . import views

app_name = "learning_path"

urlpatterns = [
    path("", views.LearningPathView.as_view(), name="paths"),
    path(
        "<slug:slug>/details/",
        views.LearningPathDetailView.as_view(),
        name="path-detail",
    ),
]

src/pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.home, name="home"),
    path("subscribe/", views.subscribe, name="subscribe"),
    path("about/", views.about, name="about"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("community/", views.community_page, name="community"),
    path("team/", views.team_page, name="team"),
    path("faq/", views.faq, name="faq"),
    path("contact/", views.ContactUsView.as_view(), name="contact"),
    path("become-teacher/", views.teacher_registration, name="become-teacher"),
    path("thanks/", views.ThanksView.as_view(), name="thanks"),
]

src/search/urls.py
from django.urls import path
from .views import SearchResultsView, SearchView

app_name = "search"

urlpatterns = [
    path("explorer/", SearchView.as_view(), name="explorer"),
    path("", SearchResultsView.as_view(), name="results"),
]

src/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profile/", views.CustomUserUpdateDetailView.as_view(), name="profile"),
    path(
        "profile/update_profile_image/",
        views.update_profile_image,
        name="update-profile-image",
    ),
    path(
        "profile/update_personal_info/",
        views.update_personal_info,
        name="update-personal-info",
    ),
    path(
        "profile/oauth-new-password/",
        views.set_password_for_oauth,
        name="oauth-new-password",
    ),
    path(
        "profile/update_password/",
        views.update_password,
        name="update-password",
    ),
    path("profile/update_social/", views.update_social, name="update-social"),
    path("profile/update_bio/", views.update_bio, name="update-bio"),
    # change password
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(template_name="change-password.html"),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="change-password-done.html"
        ),
        name="password_change_done",
    ),
    # reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="reset-password.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="reset-password-done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="reset-password-confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="reset-password-complete.html"
        ),
        name="password_reset_complete",
    ),
]

src/xarala/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    path("x-yarou/", admin.site.urls),
    path("graphql/", csrf_exempt(GraphQLView.as_view(graphiql=settings.DEBUG))),
    path("", include("pages.urls", namespace="pages")),
    path("courses/", include("course.urls", namespace="course")),
    path("podcasts/", include("podcast.urls", namespace="podcast")),
    path("users/", include("users.urls")),
    path("tutorials/", include("blog.urls", namespace="blog")),
    path("paths/", include("learning_path.urls", namespace="learning_path")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("news/", include("events.urls", namespace="events")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("order.urls", namespace="orders")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("search/", include("search.urls", namespace="search")),
    path("summernote/", include("django_summernote.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    PasswordChangeForm,
)

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label="Mot de passe",
        widget=forms.PasswordInput(
            {
                "class": "border w-full py-2 px-3 text-grey-darker mt-",
                "placeholder": "Mot de passe",
            }
        ),
    )
    password2 = forms.CharField(
        label="Mot de passe",
        widget=forms.PasswordInput(
            {
                "class": "border w-full py-2 px-3 text-grey-darker mt-",
                "placeholder": "Mot de passe",
            }
        ),
    )

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ("email", "password1")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("email", "avatar")


class CustomUserLoginForm(forms.Form):
    email = forms.CharField(
        max_length=254,
        label="Votre Email",
        widget=forms.TextInput(
            {
                "class": "border w-full py-2 px-3 text-grey-darker mt-",
                "placeholder": "Email",
            }
        ),
    )
    password = forms.CharField(
        label="Mot de passe",
        widget=forms.PasswordInput(
            {
                "class": "border w-full py-2 px-3 text-grey-darker mt-",
                "placeholder": "Mot de passe",
            }
        ),
    )
    # avatar = forms.ImageField()


class CustomUserProfileForm(forms.ModelForm):
    avatar = forms.ImageField(
        label="Photo de profile",
    )

    class Meta:
        model = CustomUser
        fields = ("avatar",)


class CustomUserUpdateForm(forms.ModelForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(max_length=80, label="Prénom")
    last_name = forms.CharField(max_length=80, label="Nom")
    phone = forms.CharField(max_length=80, label="Numéro de téléphone")
    address = forms.CharField(max_length=80, label="Adresse")
    title = forms.CharField(max_length=80, label="Titre")

    class Meta:
        model = CustomUser
        fields = (
            "first_name",
            "last_name",
            "email",
            "title",
            "phone",
            "address",
        )


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.FileField(
        label="Photo de profile",
        widget=forms.FileInput(
            {
                "class": "opacity-0 position-absolute as-parent file-upload",
                "accept": "image/*",
            }
        ),
    )

    class Meta:
        model = CustomUser
        fields = ("avatar",)


class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(
        max_length=80, label="Mot de passe actuel", widget=forms.PasswordInput()
    )
    new_password1 = forms.CharField(
        max_length=80, label="Nouveau mot de passe", widget=forms.PasswordInput()
    )
    new_password2 = forms.CharField(
        max_length=80, label="Confirmation mot de passe", widget=forms.PasswordInput()
    )

    class Meta:
        model = CustomUser


class UpdateSocialForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = (
            "facebook",
            "twitter",
            "linkedin",
            "github",
        )


class UpdateBioForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ("bio",)

src/xarala/templates/partials/_blog-list.html
{% load static %}
{% if posts %}

{% for post in posts %}

<div class="list-card marginTop-40">

  <div class="col-md-4 px-md-0">
    <a href="{{ post.get_absolute_url }}">
      <img class="w-100" src="
          {% if post.thumbnail %}
          {{ post.thumbnail.url }}
          {% elif post.image_url %}
          {{ post.image_url }}
          {% else %}{% static 'images/logo.png'  %}
          {% endif %}" alt="{{ post.title }}">
    </a>
  </div>

  <div class="col-md-8 px-md-0">
    <div class="card height-100p shadow-v1">
      <div class="card-body">
        <a href="{{ post.get_absolute_url }}" class="h4 mb-3">
          {{ post.title }}
        </a>
        <p class="mb-0">
          {{ post.description|safe|truncatewords:"20" }}
        </p>
      </div>
      <div class="card-footer">
        <div class="media">
          <img class="iconbox" src="{% if post.author.avatar %} {{ post.author.avatar.url }} {% else %} {% static 'images/logo.png' %}
            {% endif %}" alt="{{ post.author.get_full_name }}">
          <div class="media-body ml-4">
            <a href="#" class="text-primary"> {{ post.author.get_full_name }}</a> <br>
            {{ post.date_created|date:"d, M, Y" }} - <a href="{% url 'blog:blog_tag' post.tags.first  %}"
              class="text-primary">dans {{ post.tags.first }}</a>
          </div>
        </div>
      </div>
    </div>
  </div> <!-- END col-md-8-->
</div> <!-- END list-card-->

{% endfor %}

{% endif %}

src/xarala/templates/partials/_breadcrumbs.html
<div class="padding-y-60 bg-cover bg-dark" data-dark-overlay="2">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 my-2 text-white">
        <ol class="breadcrumb breadcrumb-double-angle bg-transparent p-0">
          <li class="breadcrumb-item"><a href="{% url 'pages:home' %}">Accueil</a></li>
          {% if previous %}
          <li class="breadcrumb-item"><a {% if instanceid %} href="{% url previous_url instanceid %}" {% else %}
              href="{% url previous_url %} {% endif %}">{{ previous }}</a></li>
          {% endif %}
          <li class="breadcrumb-item">{{ current }}</li>
        </ol>
        <h2 class="h1">
          {{ current }}
        </h2>
        <p class="lead">{{ text }}
        </p>
      </div>
      <form class="col-lg-5 my-2 ml-auto" method='GET' action="{% url 'search:results' %}">
        <div class="input-group bg-white rounded p-1">
          <input type="text" class="form-control border-white" placeholder="Que souhaitez-vous apprendre?" name="q"
            required>
          <div class="input-group-append">
            <button class="btn btn-primary rounded" type="submit">
              Rechercher
              <i class="ti-angle-right small"></i>
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

src/xarala/templates/partials/_footer.html
{% load static %}

<footer class="footer mt-30">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="item_f1">
                    <a href="{% url 'blog:posts' %}">Tutoriels</a>
                    <a href="{% url 'course:courses' %}">Cours</a>
                    <a href="{% url 'learning_path:paths' %}">Parcours</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="item_f1">
                    <a href="{% url 'pages:contact' %}">Nous contacter</a>
                    <a href="{% url 'pages:about' %}">À propos</a>
                    <a href="{% url 'pages:community' %}">Communauté</a>

                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="item_f1">
                    <a href="{% url 'pages:faq' %}">FAQ</a>
                    <a href="{% url 'pages:privacy_policy' %}">Politique de confidentialité</a>
                    <a href="#">Sitemap</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6">
                <div class="item_f3">
                    <a href="{% url 'register' %}" class="btn1542">Enseigner sur Xarala</a>
                    <div class="lng_btn">
                        <div class="ui language bottom right pointing dropdown floating" id="languages" data-content="Select Language">
                            <a href="#"><i class='uil uil-globe lft'></i>Langue<i class='uil uil-angle-down rgt'></i></a>
                            <div class="menu">
                                <div class="scrolling menu">
                                    <div class="item" data-percent="100" data-value="en" data-english="English">
                                        <span class="description">English</span> English
                                    </div>
                                    <div class="item" data-percent="94" data-value="da" data-english="Français">
                                        <span class="description">french</span> Français
                                    </div>
                                    <div class="item" data-percent="94" data-value="es" data-english="Wolof">
                                        <span class="description">Wolof</span> Wolof
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="footer_bottm">
                    <div class="row">
                        <div class="col-md-6">
                            <ul class="fotb_left">
                                <li>
                                    <a href="/">
                                        <div class="footer_logo">
                                            <img src="{% static 'images/logo1.svg' %}" alt="">
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <p>© 2021 <strong>Xarala</strong>. Tous droits réservés.</p>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-6">
                            <div class="edu_social_links">
                                <a target="_blank" href="https://web.facebook.com/xarala"><i class="fab fa-facebook-f"></i></a>
                                <a target="_blank" href="https://twitter.com/xaralatech"><i class="fab fa-twitter"></i></a>
                                <a target="_blank" href="https://linkedin.com/in/xarala221"><i class="fab fa-linkedin-in"></i></a>
                                <a target="_blank" href="https://linkedin.com/in/xarala221"><i class="fab fa-instagram"></i></a>
                                <a target="_blank" href="http://bit.ly/xaralaYouTube"><i class="fab fa-youtube"></i></a>
                                <a target="_blank" href="https://discord.gg/2gZqqp5"><i class="fab fa-discord"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

src/xarala/templates/partials/_sidebar_instructor.html
{% load static %}

<ul>


    <div class="left_section">
        <h6 class="left_title">Cours</h6>
        <ul>
            <li class="menu--item">
                <a href="{% url 'dashboard:courses' %}" class="menu--link" title="Vos cours">
                    <i class='uil uil-video menu--icon'></i>
                    <span class="menu--label">Vos cours</span>
                </a>
            </li>
            <li class="menu--item">
                <a href="{% url 'dashboard:create-course' %}" class="menu--link" title="Nouveau cours">
                    <i class='uil uil-plus-circle menu--icon'></i>
                    <span class="menu--label">Nouveau cours</span>
                </a>
            </li>
        </ul>
    </div>



    <div class="left_section">
        <h6 class="left_title">Tutoriels</h6>
        <ul>
            <li class="menu--item">
                <a href="{% url 'dashboard:tutorials' %}" class="menu--link" title="Vos tutos">
                    <i class='uil uil-book-reader menu--icon'></i>
                    <span class="menu--label">Vos tutos</span>
                </a>
            </li>
            <li class="menu--item">
                <a href="{% url 'dashboard:create-tutorial' %}" class="menu--link" title="Nouveau tutoriel">
                    <i class='uil uil-plus-circle menu--icon'></i>
                    <span class="menu--label">Nouveau tutoriel</span>
                </a>
            </li>
        </ul>
    </div>


    <li class="menu--item">
        <a href="instructor_notifications.html" class="menu--link" title="Notifications">
            <i class="uil uil-bell menu--icon"></i>
            <span class="menu--label">Notifications</span>
        </a>
    </li>
    {% if request.user.is_student %}
    <li class="menu--item">
        <a href="instructor_my_certificates.html" class="menu--link" title="My Certificates">
            <i class="uil uil-award menu--icon"></i>
            <span class="menu--label">Mes Certificats</span>
        </a>
    </li>
    {% endif %}
</ul>

src/xarala/templates/partials/_teacher_sidebar.html
<ul>

  <div class="left_section">
    <h6 class="left_title">Cours</h6>
    <ul>
      <li class="menu--item">
        <a href="{% url 'dashboard:courses' %}" class="menu--link" title="Vos cours">
          <i class='uil uil-video menu--icon'></i>
          <span class="menu--label">Vos cours</span>
        </a>
      </li>

      <li class="menu--item">
        <a href="{% url 'dashboard:create-course' %}" class="menu--link" title="Nouveau cours">
          <i class='uil uil-plus-circle menu--icon'></i>
          <span class="menu--label">Nouveau cours</span>
        </a>
      </li>
    </ul>
  </div>



  <div class="left_section">
    <h6 class="left_title">Tutoriels</h6>
    <ul>
      <li class="menu--item">
        <a href="{% url 'dashboard:tutorials' %}" class="menu--link" title="Vos tutos">
          <i class='uil uil-book-reader menu--icon'></i>
          <span class="menu--label">Vos tutos</span>
        </a>
      </li>

      <li class="menu--item">
        <a href="{% url 'dashboard:create-tutorial' %}" class="menu--link" title="Nouveau tutoriel">
          <i class='uil uil-plus-circle menu--icon'></i>
          <span class="menu--label">Nouveau tutoriel</span>
        </a>
      </li>
    </ul>
  </div>


  <li class="menu--item">
    <a href="instructor_notifications.html" class="menu--link" title="Notifications">
      <i class="uil uil-bell menu--icon"></i>
      <span class="menu--label">Notifications</span>
    </a>
  </li>

</ul>

src/xarala/templates/partials/_tutorials_table.html
<div class="table-responsive mt-30">
  <table class="table ucp-table">
    <thead class="thead-s">
      <tr>
        <th class="text-center" scope="col">#</th>
        <th>Titre</th>
        <th class="text-center" scope="col">Date de création</th>
        <th class="text-center" scope="col">Catégorie</th>
        <th class="text-center" scope="col">Statut</th>
        <th class="text-center" scope="col">Action</th>
      </tr>
    </thead>
    <tbody>

      {% for tutorial in tutorials %}
      <tr>
        <td class="text-center">{{ forloop.counter }}</td>
        <td>{{ tutorial.title }}</td>
        <td class="text-center">{{ tutorial.created_at|date:"d-m-Y" }}</td>
        <td class="text-center">
          {% for tag in tutorial.tags.all %}
          <a href="#">{{ tag.name|default_if_none:"" }}</a> {% endfor %}
        </td>
        <td class="text-center"><b class="course_active">
            {% if tutorial.published %}
            Publié
            {% elif tutorial.submitted %}
            Soumis
            {% else %}
            En attente
            {% endif %}
          </b></td>
        <td class="text-center">
          <div class="dropdown">
            <a class="btn" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              <i class="fas fa-ellipsis-v"></i>
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <button class="btn"><a href="{% url 'blog:blog-detail' tutorial.slug %}" title="View"
                  class="dropdown-item">Détails</a>
              </button>
              {% if user.is_teacher or user.is_student %}
              {% if not tutorial.submitted and not tutorial.published %}
              <button id="submit_tutorial" tutorial_id="{{tutorial.id}}" class="btn"><a href="#" title="Submit"
                  class="dropdown-item">Soumettre</a>
              </button>
              {% endif %}
              <button class="btn"><a href="{% url 'dashboard:update-tutorial' tutorial.id %}" title="Edit"
                  class="dropdown-item">Modifier</a>
              </button>
              {% endif %}

              {% if user.is_staff and tutorial.submitted %}
              <button tutorial_id="{{tutorial.id}}" class="btn btn-sm  publish_tutorial"><a href="#" title="Publish"
                  class="dropdown-item">Publier</a>
              </button>
              {% endif %}
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}

    </tbody>
  </table>

  {% include "partials/_pagination.html" %}
</div>