src/blog/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from blog.sitemaps import PostSitemap

from . import views

app_name = "blog"
sitemaps = {"posts": PostSitemap}

urlpatterns = [
    path("", views.PostListView.as_view(), name="posts"),
    path("<slug:slug>/", views.PostDetailView.as_view(), name="blog-detail"),
    path("tutorials/tags/<str:tag_name>/", views.blog_tag, name="blog_tag"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

src/course/urls.py
from django.urls import path
from . import views

app_name = "course"


urlpatterns = [
    path("", views.CourseListView.as_view(), name="courses"),
    path(
        "<slug:slug>/overview",
        views.CourseOverviewView.as_view(),
        name="course-overview",
    ),
    path("<slug:slug>/", views.CourseDetailView.as_view(), name="course-detail"),
    path(
        "subscribe-user-to-course/<slug:course_slug>/",
        views.subscribe_user_to_course,
        name="subscribe_user_to_course",
    ),
    path(
        "category/<str:category>/",
        views.CategoryCourseList.as_view(),
        name="course-by-category",
    ),
]

src/events/urls.py
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
    path("", views.EventListView.as_view(), name="events"),
    path("<slug:slug>/", views.EventDetailView.as_view(), name="event-detail"),
]

src/pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.home, name="home"),
    path("subscribe/", views.subscribe, name="subscribe"),
    path("about/", views.about, name="about"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("community/", views.community_page, name="community"),
    path("team/", views.team_page, name="team"),
    path("faq/", views.faq, name="faq"),
    path("contact/", views.ContactUsView.as_view(), name="contact"),
    path("become-teacher/", views.teacher_registration, name="become-teacher"),
    path("thanks/", views.ThanksView.as_view(), name="thanks"),
]

src/search/urls.py
from django.urls import path
from .views import SearchResultsView, SearchView

app_name = "search"

urlpatterns = [
    path("explorer/", SearchView.as_view(), name="explorer"),
    path("", SearchResultsView.as_view(), name="results"),
]

src/xarala/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    path("x-yarou/", admin.site.urls),
    path("graphql/", csrf_exempt(GraphQLView.as_view(graphiql=settings.DEBUG))),
    path("", include("pages.urls", namespace="pages")),
    path("courses/", include("course.urls", namespace="course")),
    path("podcasts/", include("podcast.urls", namespace="podcast")),
    path("users/", include("users.urls")),
    path("tutorials/", include("blog.urls", namespace="blog")),
    path("paths/", include("learning_path.urls", namespace="learning_path")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("news/", include("events.urls", namespace="events")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("order.urls", namespace="orders")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("search/", include("search.urls", namespace="search")),
    path("summernote/", include("django_summernote.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/xarala/templates/_auth_base.html
<!DOCTYPE html>

<html lang="fr">
{% load static %}

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143511541-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-143511541-1');
  </script>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, shrink-to-fit=9">
  <meta name="description" content="Xarala Academy La technologie dans votre langue">
  <meta name="keywords"
    content="Xarala Academy, Xarala, Apprendre à coder, Apprendre Python, Formation Xarala, Formation Python">
  <meta name="author" content="xarala">
  <title> Xarala Academy |
    {% block title %} Accueil, Cours en ligne - La technologie dans votre langue
    {% endblock title %}</title>

  <!-- Favicon Icon -->
  <link rel="icon" type="image/png" href="{% static 'images/logo.png' %}">

  <!-- Stylesheets -->
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,500' rel='stylesheet'>
  <link href='{% static "vendor/unicons-2.0.1/css/unicons.css" %}' rel='stylesheet'>
  <link href="{% static 'css/vertical-responsive-menu.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
  <link href="{% static 'css/night-mode.css' %}" rel="stylesheet">

  <!-- Vendor Stylesheets -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/OwlCarousel/assets/owl.carousel.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/OwlCarousel/assets/owl.theme.default.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/semantic/semantic.min.css' %}">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  {% block extrastyle %} {% endblock extrastyle %}
</head>

<body>

  <div class="sign_in_up_bg">
    <div class="container">
      <div class="row justify-content-lg-center justify-content-md-center">
        <div class="col-lg-12">
          <div class="py-4 text-center" id="logo">
            <a href="/"><img src="{% static 'images/logo.png' %}" alt="Logo Xarala" width="70"></a>
            <a href="/"><img class="logo-inverse" src="{% static 'images/logo.png' %}" alt="Logo Xarala" width="70"></a>
          </div>
        </div>


        {% block content %}

        {% endblock content %}


      </div>
    </div>
  </div>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/OwlCarousel/owl.carousel.js' %}"></script>
  <script src="{% static 'vendor/semantic/semantic.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script src="{% static 'js/night-mode.js' %}"></script>
  {% block extrajs %} {% endblock extrajs %}
</body>

</html>

src/xarala/templates/_base.html
<!DOCTYPE html>

<html lang="fr">
{% load static %}

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143511541-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'UA-143511541-1');
  </script>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, shrink-to-fit=9">

  {% block meta %}
  <meta name="description" property="og:description" content="Xarala Academy La technologie dans votre langue">
  <meta name="keywords"
    content="Formation, Xarala Academy, Xarala, Apprendre à coder, Apprendre Python, Formation Xarala, Formation Python">
  <meta name="author" content="xarala">
  <meta property="og:title" content="Xarala Academy">
  <meta name="description" property="og:description" content="Xarala Academy La technologie dans votre langue">
  <meta property="og:image" content="{% static 'images/logo.jpg' %}">
  <meta property="og:image:alt" content="Logo Xarala">
  <meta property="og:url" content="{{ request.get_host }}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@xaralatech">
  <meta name="twitter:creator" content="@xaralatech">
  <meta name="twitter:title" content="Xarala Academy">
  <meta name="twitter:description" content="Xarala, La technologie dans votre langue.">
  <meta name="twitter:image" content="{% static 'images/logo.jpg' %}">
  <meta name="twitter:image:alt" content="Logo de Xarala.">
  {% endblock meta %}
  <title> Xarala Academy - {% block title %} Accueil, Cours en ligne - La technologie dans votre langue
    {% endblock title %}
  </title>

  <!-- Favicon Icon -->
  <link rel="icon" type="image/png" href="{% static 'images/logo.jpg' %}">

  <!-- Stylesheets -->
  <!-- <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,500' rel='stylesheet'> -->
  <link href='{% static "vendor/unicons-2.0.1/css/unicons.css" %}' rel='stylesheet'>
  <link href="{% static 'css/vertical-responsive-menu.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
  <!-- <link href="{% static 'css/night-mode.css' %}" rel="stylesheet"> -->

  <!-- Vendor Stylesheets -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/OwlCarousel/assets/owl.carousel.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/OwlCarousel/assets/owl.theme.default.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/semantic/semantic.min.css' %}">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  {% block extrastyle %} {% endblock extrastyle %}
</head>

<body>
  <!-- Header Start -->
  {% include "partials/_header.html" %}
  <!-- Header End -->
  <!-- Left Sidebar Start -->
  <nav class="vertical_nav">
    <div class="left_section menu_left" id="js-menu">
      <div class="left_section">
        <ul>

          {% if user.is_authenticated %}
          <li class="menu--item">
            <a href="{% url 'dashboard:dashboard' %}"
              class="menu--link {% if 'dashboard' in request.path %} active {% endif %}" title="Tableau de Bord">
              <i class='uil uil-dashboard menu--icon'></i>
              <span class="menu--label">Tableau de Bord</span>
            </a>
          </li>
          {% endif %}

          <div class="left_section">
            <h6 class="left_title">La plateforme</h6>
            <ul>
              <li class="menu--item">
                <a href="{% url 'course:courses' %}" class="menu--link" title="Cours">

                  <i class='uil uil-video menu--icon'></i>
                  <span class="menu--label">Cours</span>
                </a>
              </li>
              <li class="menu--item">
                <a href="{% url 'blog:posts' %}" class="menu--link" title="Tutoriels">

                  <i class='uil uil-book-reader menu--icon'></i>
                  <span class="menu--label">Tutoriels</span>
                </a>
              </li>
              <li class="menu--item">
                <a href="{% url 'search:explorer' %}" class="menu--link" title="Explorer">
                  <i class='uil uil-search menu--icon'></i>
                  <span class="menu--label">Explorer</span>
                </a>
              </li>

              <li class="menu--item">
                <a href="{% url 'learning_path:paths' %}" class="menu--link" title="Parcours">

                  <i class='uil uil-book menu--icon'></i>
                  <span class="menu--label">Parcours</span>
                </a>
              </li>
            </ul>
          </div>

        </ul>
      </div>


      <div class="left_section pt-2">
        <ul>
          <li class="menu--item">
            <a href="{% url 'pages:about' %}" class="menu--link" title="Setting">
              <i class='uil uil-cog menu--icon'></i>
              <span class="menu--label">À propos</span>
            </a>
          </li>
          <li class="menu--item">
            <a href="{% url 'events:events' %}" class="menu--link" title="Feedback">
              <i class='uil uil-windsock menu--icon'></i>
              <span class="menu--label">Actualités</span>
            </a>
          </li>
        </ul>
      </div>
      <div class="left_footer">
        <ul>
          <li><a href="{% url 'pages:about' %}">À propos</a></li>
          <li><a href="{% url 'pages:contact' %}">Nous contacter</a></li>
        </ul>
        <div class="left_footer_content">
          <p>© 2021 <strong>Xarala</strong>. Tous droits réservés.</p>
        </div>
      </div>
    </div>
  </nav>
  <!-- Left Sidebar End -->
  <!-- Body Start -->
  <div class="wrapper">

    <div class="sa4d25">
      <div class="container-fluid">
        {% include "partials/_alerts.html" %}
        {% if user.is_authenticated and not user.has_usable_password %}
        <div class="text-center pt-4 mt-4">
          <div class="alert alert-danger" role="alert">
            <a href="{% url 'oauth-new-password' %}" class="text-danger">Cliquez ici pour ajouter un mot de
              passe</a>
          </div>
        </div>
        {% else %}

        {% endif %}
        <div class="row">
          <div class="col-xl-12 col-lg-12">

            {% block content %}

            {% endblock content %}

          </div>

          <!-- testimonials -->
        </div>
      </div>
    </div>
    {% include "partials/_footer.html" %}
  </div>

  <script src="{% static 'js/vertical-responsive-menu.min.js' %}"></script>
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/OwlCarousel/owl.carousel.js' %}"></script>


  <script src="{% static 'vendor/semantic/semantic.min.js' %}"></script>


  <script src="{% static 'js/custom.js' %}"></script>
  <!-- <script src="{% static 'js/night-mode.js' %}"></script> -->
  {% block extrajs %} {% endblock extrajs %}
</body>

</html>