src/blog/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from blog.sitemaps import PostSitemap

from . import views

app_name = "blog"
sitemaps = {"posts": PostSitemap}

urlpatterns = [
    path("", views.PostListView.as_view(), name="posts"),
    path("<slug:slug>/", views.PostDetailView.as_view(), name="blog-detail"),
    path("tutorials/tags/<str:tag_name>/", views.blog_tag, name="blog_tag"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

src/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:course_id>/", views.cart_add, name="cart_add"),
    path(
        "add-to-cart/<str:course_slug>/",
        views.add_course_to_cart,
        name="add_course_to_cart",
    ),
    path("remove/<int:course_id>/", views.cart_remove, name="cart_remove"),
]

src/course/urls.py
from django.urls import path
from . import views

app_name = "course"


urlpatterns = [
    path("", views.CourseListView.as_view(), name="courses"),
    path(
        "<slug:slug>/overview",
        views.CourseOverviewView.as_view(),
        name="course-overview",
    ),
    path("<slug:slug>/", views.CourseDetailView.as_view(), name="course-detail"),
    path(
        "subscribe-user-to-course/<slug:course_slug>/",
        views.subscribe_user_to_course,
        name="subscribe_user_to_course",
    ),
    path(
        "category/<str:category>/",
        views.CategoryCourseList.as_view(),
        name="course-by-category",
    ),
]

src/xarala/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    path("x-yarou/", admin.site.urls),
    path("graphql/", csrf_exempt(GraphQLView.as_view(graphiql=settings.DEBUG))),
    path("", include("pages.urls", namespace="pages")),
    path("courses/", include("course.urls", namespace="course")),
    path("podcasts/", include("podcast.urls", namespace="podcast")),
    path("users/", include("users.urls")),
    path("tutorials/", include("blog.urls", namespace="blog")),
    path("paths/", include("learning_path.urls", namespace="learning_path")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("news/", include("events.urls", namespace="events")),
    path("cart/", include("cart.urls", namespace="cart")),
    path("orders/", include("order.urls", namespace="orders")),
    path("coupons/", include("coupons.urls", namespace="coupons")),
    path("payment/", include("payment.urls", namespace="payment")),
    path("search/", include("search.urls", namespace="search")),
    path("summernote/", include("django_summernote.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/course/models.py
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.db.models import Sum
from django.utils.text import slugify
from course.managers import CourseManager, LessonManager
from users.models import CustomUser
from xarala.utils import upload_image_path
from xarala.constants import (
    YOUTUBE,
    VIMEO,
    CLOUDINARY,
    CUSTOM,
    WISTA,
    BEGINNER,
    INTERMEDIATE,
    MEDIUM,
    ALL_LEVELS,
)
from .fields import OrderField


class Language(models.Model):
    name = models.CharField(max_length=50)
    abr = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name} - {self.abr}"


class Category(models.Model):
    name = models.CharField(max_length=200)
    icon = models.CharField(max_length=50, default="uil-arrow")
    description = models.TextField()
    thumbnail = models.FileField(upload_to=upload_image_path, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("course:course-by-category", kwargs={"category": self.name})

    class Meta:
        verbose_name_plural = "Categories"


class Course(models.Model):
    LEVEL = (
        (BEGINNER, BEGINNER),
        (MEDIUM, MEDIUM),
        (INTERMEDIATE, INTERMEDIATE),
        (ALL_LEVELS, ALL_LEVELS),
    )
    title = models.CharField(max_length=200)
    description = models.TextField()
    short_description = models.TextField(
        default="Dans ce cours, vous allez apprendre..."
    )
    discount = models.DecimalField(default=0, max_digits=13, decimal_places=2)
    price = models.DecimalField(default=0, max_digits=13, decimal_places=2)
    level = models.CharField(max_length=150, choices=LEVEL, default=BEGINNER)
    featured = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, unique=True, null=True, blank=True)
    thumbnail = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    teacher = models.ForeignKey(
        CustomUser,
        models.SET_NULL,
        null=True,
        related_name="courses_created",
        verbose_name="teacher",
    )
    students = models.ManyToManyField(
        CustomUser, related_name="courses_enrolled", blank=True
    )
    categories = models.ManyToManyField(Category, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    language = models.ForeignKey(Language, models.SET_NULL, null=True)
    drafted = models.BooleanField(default=False)
    published = models.BooleanField(default=False)
    submitted = models.BooleanField(default=False)
    publish_date = models.DateTimeField(auto_now_add=False, blank=True, null=True)
    promote_video = models.TextField(null=True)

    objects = CourseManager()

    class Meta:
        ordering = ["-date_created"]

    def __str__(self):
        return self.title

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Course.objects.filter(slug=unique_slug).exists():
            unique_slug = "{}-{}".format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def get_introudction(self):
        lesson = Lesson.objects.filter(chapter__in=self.get_chapters()).first()
        return lesson

    def get_chapters(self):
        chapters = Chapter.objects.filter(course=self).order_by("id")
        return chapters

    def get_lessons(self):
        lessons = Lesson.objects.filter(chapter__in=self.get_chapters()).order_by(
            "order"
        )
        return lessons

    def count_lessons(self):
        lessons = Lesson.objects.filter(chapter__in=self.get_chapters()).count()
        return lessons

    def count_duration(self):
        text = "Mns"
        lessons = Lesson.objects.filter(chapter__in=self.get_chapters())
        get_duration = lessons.aggregate(Sum("duration"))["duration__sum"]
        if get_duration:
            if get_duration >= 60:
                get_duration = get_duration / 60
                text = " Hrs"
        else:
            get_duration = 0
        return f"{round(get_duration,2)} {text}"

    def count_students(self):
        total_students = self.students.count()
        return total_students

    def get_absolute_url(self):
        return reverse("course:course-overview", kwargs={"slug": self.slug})


class Chapter(models.Model):
    name = models.CharField(max_length=150)
    course = models.ForeignKey(
        Course, models.SET_NULL, null=True, related_name="course_chapters"
    )
    slug = models.SlugField(max_length=200, unique=True, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    drafted = models.BooleanField(default=False)
    order = OrderField(blank=True, null=True, for_fields=["course"])

    def __str__(self):
        return self.name

    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Chapter.objects.filter(slug=unique_slug).exists():
            unique_slug = "{}-{}".format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def get_lessons(self):
        lessons = Lesson.objects.filter(chapter=self).order_by("order")
        return lessons

    class Meta:
        ordering = ["id"]


class Lesson(models.Model):

    PLATFORM = (
        (YOUTUBE, YOUTUBE),
        (VIMEO, VIMEO),
        (WISTA, WISTA),
        (CUSTOM, CUSTOM),
        (CLOUDINARY, CLOUDINARY),
    )
    title = models.CharField(max_length=200)
    is_video = models.BooleanField(default=True)
    text = models.TextField(blank=True)
    order = OrderField(blank=True, null=True, for_fields=["chapter"])
    slug = models.SlugField(max_length=200, unique=True, null=True, blank=True)
    file = models.FileField(upload_to=upload_image_path, blank=True, null=True)
    video_url = models.CharField(max_length=240, null=True, blank=True)
    video_id = models.CharField(max_length=150, null=True, blank=True)
    duration = models.IntegerField(default=0)
    platform = models.CharField(max_length=50, choices=PLATFORM, default=YOUTUBE)
    chapter = models.ForeignKey(
        Chapter, models.SET_NULL, null=True, blank=True, related_name="course_lessons"
    )
    drafted = models.BooleanField(default=False)
    preview = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    objects = LessonManager()

    def __str__(self):
        return self.title

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Lesson.objects.filter(slug=unique_slug).exists():
            unique_slug = "{}-{}".format(slug, num)
            num += 1
        return unique_slug

    def next(self):
        try:
            next_lesson = Lesson.objects.filter(
                Q(
                    lecture_number=self.lecture_number + 1,
                    chapter__course__id=self.chapter.course.id,
                    chapter__id=self.chapter.id,
                )
            )
            return next_lesson.get().slug
        except Exception:
            return None

    def previous(self):
        try:
            previous_lesson = Lesson.objects.filter(
                Q(
                    lecture_number=self.lecture_number - 1,
                    chapter__course__id=self.chapter.course.id,
                    chapter__id=self.chapter.id,
                )
            )
            return previous_lesson.get().slug
        except Exception:
            return None

    class Meta:
        ordering = ["order"]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

src/course/templates/course_detail.html
{% extends "_base.html" %}

{% block title %}
{{ lesson.title }}
{% endblock title %}

{% block content %}

<div class="sa4d25">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-8 col-lg-8">
        <div class="section3125">
          <div class="live1452">
            <iframe src="https://www.youtube.com/embed/{{ lesson.video_id }}?rel=0?autoplay=1"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="user_dt5">
            {{ lesson.text|safe }}
            <!-- <div class="row">
              <div class="col-md-12">
                <div class="blog_pagination">
                  <a href="#" class="bp_left">
                    <i class="uil uil-angle-double-left"></i>
                    <div class="kslu15">
                      <div class="prevlink">Précédent</div>
                      <div class="prev_title">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div>
                    </div>
                  </a>
                  <a href="#" class="bp_right">
                    <div class="kslu16">
                      <div class="prevlink1">Suivant</div>
                      <div class="prev_title1">Vestibulum vulputate nulla quis dignissim ultricies.</div>
                    </div>
                    <i class="uil uil-angle-double-right"></i>
                  </a>
                </div>
              </div>
            </div> -->

          </div>
        </div>
      </div>
      <div class="col-xl-4 col-lg-4">
        <div class="right_side">
          <div class="fcrse_3">
            <div class="cater_ttle">
              <h4>Contenu du cours</h4>
            </div>
            <div class="live_chat">
              <div class="mb-2">
                {% if object.course_chapters.all %}
                {% for chapter in object.course_chapters.all %}

                <h5>Section {{ forloop.counter }}: {{ chapter.name }}</h5>

                {% if chapter.course_lessons.all  %}
                {% for lesson in chapter.course_lessons.all  %}
                {% if lesson.chapter.id == chapter.id %}

                <p class="ml-2">
                  {{ forloop.counter }}:
                  <a href="{% url 'course:course-detail' object.slug %}?lecture={{lesson.slug}}"
                    class="{% if lesson.slug in request.get_full_path %} text-primary {% else %} text-dark  {% endif %}">
                    {{ lesson.title }}</a>
                </p>
                {% endif %}
                {% endfor %}
                {% endif %}

                {% endfor %}
                {% endif %}
              </div>
            </div>
            <!-- prise de notes -->
            <!-- <div class="live_comment">
              <input class="live_input" type="text" placeholder="Say Something..." />
              <button class="btn_live"><i class='uil uil-message'></i></button>
            </div> -->
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock content %}

src/course/templates/course_list.html
{% extends "_base.html" %}
{% load static %}

{% block title %}
Tous les cours
{% endblock title %}

{% block meta %}
<meta property="og:title" content="Tous les cours de Xarala">
<meta name="description" property="og:description" content="Formation pratique et simple.">
<meta property="og:image" content="{% static 'images/logo.png' %}">
<meta property="og:image:alt" content="Logo Xarala">
<meta property="og:url" content="{{ request.get_host }}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@xaralatech">
<meta name="twitter:creator" content="@xaralatech">
<meta name="twitter:title" content="Xarala Academy">
<meta name="twitter:description" content="Formation pratique et simple.">
<meta name="twitter:image" content="{% static 'images/logo.png' %}">
<meta name="twitter:image:alt" content="Logo de Xarala.">
{% endblock meta %}

{% block content %}
<div class="section3125">
  <div class="sa4d25">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xl-12 col-lg-12">

          <h4 class="item_title">Cours en vedette</h4>
          <div class="la5lo1">
            <div class="owl-carousel featured_courses owl-theme">
              {% for course in courses %}
              {% include "partials/_course-card.html" with course=course %}
              {% endfor %}
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<div class="section3125">
  <div class="sa4d25">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xl-12 col-lg-12">
          <h4 class="item_title">Cours populaires</h4>
          <div class="la5lo1">
            <div class="owl-carousel featured_courses owl-theme">
              {% for course in courses %}
              {% include "partials/_course-card.html" with course=course %}
              {% endfor %}
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<!-- course by category -->
{% for category in categories %}
<div class="section3125">
  <div class="sa4d25">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xl-12 col-lg-12">
          <h4 class="item_title">{{ category }}</h4>
          <div class="la5lo1">
            <div class="owl-carousel featured_courses owl-theme">
              {% for course in category.course_set.published %}
              {% include "partials/_course-card.html" with course=course %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}


{% endblock content %}

src/course/templates/course_overview.html
{% extends "_base.html" %}
{% load static %}
{% load embed_video_tags %}

{% block title %}
{{ course.title }}
{% endblock title %}

{% block meta %}
<meta property="og:title" content="{{ course.title }}">
<meta name="description" property="og:description" content="{{ course.title }}.">
<meta property="og:image"
  content="{% if course.thumbnail %} {{ course.thumbnail.url }} {% else %} {% static 'images/logo.png' %} {% endif %}">
<meta property="og:image:alt" content="Logo Xarala">
<meta property="og:url" content="{{ request.get_host }}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@xaralatech">
<meta name="twitter:creator" content="@xaralatech">
<meta name="twitter:title" content="{{ course.title }}">
<meta name="twitter:description" content="{{ course.title }}.">
<meta name="twitter:image"
  content="{% if course.thumbnail %} {{ course.thumbnail.url }} {% else %} {% static 'images/logo.png' %} {% endif %}">
<meta name="twitter:image:alt" content="Logo de Xarala.">
{% endblock meta %}

{% block content %}

<div class="section3125">

  <div class="modal vd_mdl fade" id="videoModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div class="modal-body">
          <iframe src="https://www.youtube.com/embed/{{ course.get_introudction.video_id }}"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>

      </div>
    </div>
  </div>

  <div class="_215b01">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="section3125">
            <div class="row justify-content-center">
              <div class="col-xl-4 col-lg-5 col-md-6">
                <div class="preview_video">
                  <a href="#" class="fcrse_img" data-toggle="modal" data-target="#videoModal">
                    <img
                      src="{% if course.thumbnail %} {{ course.thumbnail.url }} {% else %} {% static 'images/logo.png' %} {% endif %}"
                      alt="{{ course.title }}">
                    <div class="course-overlay">
                      <div class="badge_seller">Recommandé</div>
                      <span class="play_btn1"><i class="uil uil-play"></i></span>
                      <span class="_215b02">Aperçu du cours</span>
                    </div>
                  </a>
                </div>
              </div>
              <div class="col-xl-8 col-lg-7 col-md-6">
                <div class="_215b03">
                  <h2>{{ course.title }}</h2>
                  <span class="_215b04"> {{ course.description|safe }}!</span>
                </div>
                <div class="_215b05">
                  <span><i class='uil uil-user'></i></span> {{ course.count_students }} Étudiants inscrits
                </div>
                <div class="_215b06">
                  <div class="_215b07">
                    <span><i class='uil uil-comment'></i></span>
                    Langue: {{ course.language.name }}
                  </div>

                </div>
                <ul class="_215b31">
                  {% if course.price == 0 %}

                  <li>
                    <button class="btn_adcart">
                      <a href="{% if button_text == 'S\'inscrire'  %}{% url 'course:subscribe_user_to_course' course.slug %}{% else %}/courses/{{ course.slug }}/?lecture={{course.get_introudction.slug}}{% endif %}"
                        class="text-light">{{ button_text }}</a>
                    </button>
                  </li>

                  {% else %}
                  <li>
                    <a href="{% url 'cart:add_course_to_cart' course.slug %}" class="text-light">
                      <button class="btn_adcart">Ajouter au panier</button>
                    </a>
                  </li>
                  {% endif %}

                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="_215b15 _byt1458">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">

          <div class="course_tabs">
            <nav>
              <div class="nav nav-tabs tab_crse justify-content-center" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active" id="nav-about-tab" data-toggle="tab" href="#nav-about" role="tab"
                  aria-selected="true">Description</a>
                <a class="nav-item nav-link" id="nav-courses-tab" data-toggle="tab" href="#nav-courses" role="tab"
                  aria-selected="false">Contenu</a>
                <a class="nav-item nav-link" id="nav-teacher-tab" data-toggle="tab" href="#nav-teacher" role="tab"
                  aria-selected="false">Formateur</a>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="_215b17">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="course_tab_content">
            <div class="tab-content" id="nav-tabContent">
              <div class="tab-pane fade show active" id="nav-about" role="tabpanel">
                <div class="fcrse_2">
                  <div class="_htg451">
                    <div class="_htg452">
                      <h3>Objectifs</h2>
                        <span> Aucun!</span>
                    </div>
                    <div class="_htg452  mt-35">
                      <h3>Description</h2>
                        <span> {{ course.description|safe }}!</span>
                    </div>
                    <div class="_htg452 mt-35">
                      <h3>Projets</h2>
                        <span> Aucun!</span>
                    </div>
                    <div class="_htg452 mt-35">
                      <h3>Pré-requis</h2>
                        <span> Aucun!</span>
                    </div>
                  </div>
                </div>


              </div>
              <div class="tab-pane fade" id="nav-courses" role="tabpanel">


                {% if object.course_chapters.all %}
                {% for chapter in object.course_chapters.all %}
                <div class="fcrse_2 mb-3">


                  <div class="card-body">
                    <h3 class="text-oc-primary-link text-xarala">Section {{ forloop.counter }}: {{ chapter.name }}</h3>

                    {% if chapter.course_lessons.all  %}
                    {% for lesson in chapter.course_lessons.all  %}
                    {% if lesson.chapter.id == chapter.id %}

                    <p class="text-muted ml-2">Leçon {{ forloop.counter }}: {{ lesson.title }}</p>

                    {% endif %}
                    {% endfor %}
                    {% endif %}


                  </div>

                </div>
                {% endfor %}
                {% endif %}


              </div>

              <div class="tab-pane fade" id="nav-teacher" role="tabpanel">
                <div class="fcrse_2">
                  <div class="tutor_img">
                    <a href="{% url 'profile' %}"><img src="{% if course.teacher.avatar %} {{ course.teacher.avatar.url }}
            {% else %} {% static 'images/logo.png' %}
            {% endif %}" alt=""></a>
                  </div>
                  <div class="tutor_content_dt">
                    <div class="tutor150">
                      <a href="{% url 'profile' %}" class="tutor_name">{{ course.teacher.get_full_name }}</a>
                      <div class="mef78" title="Verify">
                        <i class="uil uil-check-circle"></i>
                      </div>
                    </div>
                    <div class="tutor_cate">{{ course.teacher.title|default_if_none:"Pas de titre" }}</div>
                    <ul class="tutor_social_links">
                      <li><a href="#" class="fb"><i class="fab fa-facebook-f"></i></a></li>
                      <li><a href="#" class="tw"><i class="fab fa-twitter"></i></a></li>
                      <li><a href="#" class="ln"><i class="fab fa-linkedin-in"></i></a></li>
                      <li><a href="#" class="yu"><i class="fab fa-youtube"></i></a></li>
                    </ul>
                    <div class="tut1250">
                      <span class="vdt15">
                        {{ course.teacher.courses_created.count }} Cours
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              <div class="fcrse_2 mt-2 text-center">
                <button class="btn_adcart btn-block">
                  <a href="{% if button_text == 'S\'inscrire'  %}{% url 'course:subscribe_user_to_course' course.slug %}{% else %}/courses/{{ course.slug }}/?lecture={{course.get_introudction.slug}}{% endif %}"
                    class="text-light">{{ button_text }}</a>
                </button>
              </div>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

</div>


{% endblock content %}

src/course/templates/courses_by_category.html
{% extends "_base.html" %}
{% load static %}

{% block title %}
Les cours sur {{ category }}
{% endblock title %}


{% block content %}
<div class="section3125">
  <div class="sa4d25">
    <div class="container-fluid">
      <div class="row">
        <div class="col-xl-12 col-lg-12">

          <h4 class="item_title">Les cours sur <span class="text-xarala">{{ category }}</span> </h4>
          <div class="la5lo1">
            <div class="owl-carousel featured_courses owl-theme">
              {% for course in course_list %}
              {% include "partials/_course-card.html" with course=course %}
              {% endfor %}
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}